/**
 * Downloads the webfonts the film needs into public/fonts and writes a
 * self-hosted @font-face stylesheet.
 *
 * Run once (`node scripts/fetch-fonts.mjs`); the output is committed. The
 * renderer must never fetch fonts from the network at render time — it adds a
 * failure mode and latency to every single render, and text silently falls
 * back to a wrong face (or, for Devanagari, to nothing) when it fails.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const OUT_DIR = path.join(process.cwd(), "public", "fonts");

const FAMILIES = [
  {
    name: "Poppins",
    css: "https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap",
    // Latin only — the Devanagari glyphs come from Noto below.
    subsets: ["latin", "latin-ext"],
  },
  {
    name: "Noto Sans Devanagari",
    css: "https://fonts.googleapis.com/css2?family=Noto+Sans+Devanagari:wght@400;500;600;700;800&display=swap",
    subsets: ["devanagari", "latin"],
  },
  {
    // Used only on the certificate scene, where a serif reads as a document
    // and Poppins reads as an app.
    name: "Playfair Display",
    css: "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;700&display=swap",
    subsets: ["latin"],
  },
];

// A desktop Chrome UA makes the API serve woff2 rather than ttf.
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

function slug(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}

/** Split the CSS into `/* subset *\/ @font-face {...}` pairs. */
function parseBlocks(css) {
  const blocks = [];
  const re = /\/\*\s*([a-z0-9-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/gi;
  let m;
  while ((m = re.exec(css)) !== null) {
    blocks.push({ subset: m[1], block: m[2] });
  }
  return blocks;
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const out = [
    "/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */",
    "",
  ];

  for (const family of FAMILIES) {
    const res = await fetch(family.css, { headers: { "User-Agent": UA } });
    if (!res.ok) throw new Error(`CSS fetch failed for ${family.name}: ${res.status}`);
    const css = await res.text();

    const blocks = parseBlocks(css).filter((b) =>
      family.subsets.includes(b.subset),
    );
    if (blocks.length === 0) {
      throw new Error(`No matching subsets found for ${family.name}`);
    }

    let index = 0;
    for (const { subset, block } of blocks) {
      const urlMatch = block.match(/url\((https:\/\/[^)]+\.woff2)\)/);
      const weightMatch = block.match(/font-weight:\s*(\d+)/);
      if (!urlMatch) continue;

      const weight = weightMatch ? weightMatch[1] : "400";
      const filename = `${slug(family.name)}-${subset}-${weight}-${index++}.woff2`;

      const fontRes = await fetch(urlMatch[1], { headers: { "User-Agent": UA } });
      if (!fontRes.ok) {
        throw new Error(`Font fetch failed: ${urlMatch[1]} ${fontRes.status}`);
      }
      const buf = Buffer.from(await fontRes.arrayBuffer());
      await writeFile(path.join(OUT_DIR, filename), buf);

      out.push(block.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url(/fonts/${filename})`));
      out.push("");
      console.log(`  ${filename}  ${(buf.length / 1024).toFixed(1)} KB`);
    }
    console.log(`${family.name}: ${index} files`);
  }

  await writeFile(path.join(OUT_DIR, "fonts.css"), out.join("\n"));
  console.log(`\nWrote ${path.join(OUT_DIR, "fonts.css")}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
